apps/login/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.landing, name='landing'),
    url(r'^process$', views.process, name='login_process'),
    url(r'^dashboard$', views.dashboard, name='dashboard'),
    url(r'^dashboard/logout$', views.logout, name='logout'),
]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('apps.login.urls', namespace='login'))
]

apps/login/models.py
from __future__ import unicode_literals
import re, bcrypt
from django.db import models


# email regex for use later on
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    def validate_registration(self,form_data):
        # will append any errors with inputs to be shown after
        errors=[]

        # changes email to lower case before running any checks on it
        # this avoids accidental duplicates
        email=form_data['email'].lower()

        # check first name first
        if form_data['first_name'] == '':
            errors.append('First name is required.')
        else:
            if len(form_data['first_name'])<2:
                errors.append('First name must have at least 2 characters.')
            if not str.isalpha(str(form_data['first_name'])):
                errors.append('First name may not contain numbers or symbols.')

        # now check last name
        if form_data['last_name'] == '':
            errors.append('Last name is required.')
        else:
            if len(form_data['last_name'])<2:
                errors.append('Last name must have at least 2 characters.')
            if not str.isalpha(str(form_data['last_name'])):
                errors.append('Last name may not contain numbers or symbols.')

        # now check email
        if email == '':
            errors.append('Email is required.')
        elif not EMAIL_REGEX.match(email):
            errors.append('Please enter a valid email.')
        if len(self.filter(email=email))>0:
            errors.append('This email address is already associated with an account.')

        # finally check password
        if not 'password' in form_data:
            errors.append('Password is required')
        else:
            if len(form_data['password'])<8:
                errors.append('Password must be at least 8 characters.')
            if form_data['password'] != form_data['pw_confirm']:
                errors.append('Passwords must match.')

        # if there are errors, will return the errors to be displayed
        if len(errors)>0:
            return {'error':errors}
        return {'success':'Successful registration attempt'}

    def validate_login(self,form_data):
        errors = []

        # changes email to lower case before running any checks on it
        email=form_data['email'].lower()

        # check email
        if not EMAIL_REGEX.match(email):
            errors.append('Please enter a valid email address.')
        elif len(self.filter(email=email))<1:
            errors.append('No account registered with this email address.')
        else:
            user = self.filter(email=email)[0]

            # check to see if password is valid iff email is ok
            if form_data['password'] == '':
                errors.append('Please enter your password.')
            elif not bcrypt.checkpw(str(form_data['password']),str(user.password)):
                errors.append('Incorrect password.')

        if len(errors)>0:
            return {'error':errors}
        return {'success':user.id}



    def register_user(self, form_data):
        user = User.objects.create()
        user.first_name = form_data['first_name']
        user.last_name = form_data['last_name']
        user.email = email.lower()
        user.password = bcrypt.hashpw(str(form_data['password']),bcrypt.gensalt())
        user.save()

        return User.objects.last()



class User(models.Model):
    first_name=models.CharField(max_length=255)
    last_name=models.CharField(max_length=255)
    email=models.CharField(max_length=255)
    password=models.CharField(max_length=255)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    objects = UserManager()

    def __repr__(self):
        return str(self.first_name)+' '+str(self.last_name)

apps/login/views.py
from django.shortcuts import render, redirect, reverse
from .models import *
from django.contrib import messages

# Create your views here.
def landing(request):
    return render(request, 'login/landing.html')

def process(request):
    print 'entered process'
    if 'register' in request.POST:
        print 'register'
        errors = User.objects.validate_registration(request.POST)
        if 'error' in errors:
            for error in errors['error']:
                messages.add_message(request, messages.INFO, error)
            return redirect(reverse('login:landing'))
        if 'success' in errors:
            user = User.objects.register_user(request.POST)
            request.session['user_id']=user.id
            return redirect(reverse('login:dashboard')) #replace this when you have another app plugged in

    if 'login' in request.POST:
        print 'login'
        errors = User.objects.validate_login(request.POST)
        if 'error' in errors:
            for error in errors['error']:
                messages.add_message(request, messages.INFO, error)
            return redirect(reverse('login:landing'))

        if 'success' in errors:
            user_id = errors['success']
            request.session['user_id']=user_id
            return redirect(reverse('login:dashboard'))

    pass #might be good to return someone to hell in this case

def dashboard(request):
    if not 'user_id' in request.session:
        # in the future I could send someone to hell here
        return redirect(reverse('landing'))
    user_id = request.session['user_id']
    user = User.objects.get(id=user_id)
    context = {
        'id':user_id,
        'first_name':user.first_name,
        'last_name':user.last_name,
        'email':user.email,
        'created_at':str(user.created_at)
    }
    return render(request, 'login/dashboard.html', context)

def logout(request):
    print 'entered logout'
    del request.session['user_id']
    return redirect(reverse('login:landing'))

apps/login/templates/login/dashboard.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Dashboard</title>
  </head>
  <body>
    <h1>Success! Welcome, {{first_name}}!</h1>
    <h4>You have been logged in.</h4>
    <form class="" action="{% url 'login:logout' %}" method="post">
      {% csrf_token %}
      <input type="submit" name="submit" value="Log Out">
    </form>
  </body>
</html>

apps/login/templates/login/landing.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Landing Page</title>
  </head>
  <body>
    <h2>Registration</h2>
    <form class="" action="{% url 'login:login_process' %}" method="post">
      {% csrf_token %}
      <label for="first_name">First Name: </label>
      <input type="text" name="first_name" value="">
      <label for="last_name">Last Name: </label>
      <input type="text" name="last_name" value="">
      <label for="email">Email: </label>
      <input type="text" name="email" value="">
      <label for="password">Password: </label>
      <input type="password" name="password" value="">
      <label for="pw_confirm">Confirm Password: </label>
      <input type="password" name="pw_confirm" value="">
      <input type="submit" name="register" value="Register">
    </form>
    {% if messages %}
      <ul>
      {% for message in messages %}
        <li>{{message}}</li>
      {% endfor %}
      </ul>
    {% endif %}

    <h2>Login</h2>
    <form class="" action="{% url 'login:login_process' %}" method="post">
      {% csrf_token %}
      <label for="email">Email: </label>
      <input type="text" name="email" value="">
      <label for="password">Password: </label>
      <input type="password" name="password" value="">
      <input type="submit" name="login" value="Login">
    </form>
  </body>
</html>